# ---
# root: true

# plugins:
#   - babel

# env:
#   node: true
#   jest: true
#   browser: true

# parser: "@babel/eslint-parser"
# # parser: "babel-eslint"

# parserOptions:
#   ecmaVersion: 2020
#   sourceType: "module"


# extends:
#   - "airbnb-base"
#   - "plugin:jest/recommended"

# rules:
#   no-console: 0
#   import/extensions: 0

---

env:
  node: true
  browser: true

extends:
  - 'airbnb-base'

parserOptions:
  ecmaVersion: latest

rules:
  no-console: 0
  import/extensions: 0
  no-param-reassign: 0
  js: 0
